POST http://localhost:8080/api/v1/group-time-table/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjUzMzg0NTMzLCJleHAiOjE2NTMzODgxMzQsInVzZXJOYW1lIjoiKzk5ODkzMjE1ODAwMCIsImlzcyI6IkRBVlJfQkFOSyJ9.B6d7xuFrWMJyCvRimTunhu1BrdbNCG1dz42CUtbQ6u0

{
  "groupId": "1",
  "timeTableId": "1"
}