POST http://localhost:8080/api/v1/room/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjUzMzc5ODIxLCJleHAiOjE2NTMzODM0MjEsInVzZXJOYW1lIjoiKzk5ODkzMjE1ODAwMCIsImlzcyI6IkRBVlJfQkFOSyJ9.ZuAttESAPLOPISnvD10yRoPU2KYI4jOAKZhkMHlP5Y0

{
  "name": "Google room",
  "capacity": "30"
}

###
GET http://localhost:8080/api/v1/room/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjUzMzI1NjI5LCJleHAiOjE2NTMzMjkyMjksInVzZXJOYW1lIjoiKzk5ODkzMjE1ODAwMCIsImlzcyI6IkRBVlJfQkFOSyJ9.atDTC62Gv35raTtW7iM2d7l_Uy0HEmWaZhCkKE7tQ_I

###
GET http://localhost:8080/api/v1/room/get/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjUzMzI1NjI5LCJleHAiOjE2NTMzMjkyMjksInVzZXJOYW1lIjoiKzk5ODkzMjE1ODAwMCIsImlzcyI6IkRBVlJfQkFOSyJ9.atDTC62Gv35raTtW7iM2d7l_Uy0HEmWaZhCkKE7tQ_I

###
PUT http://localhost:8080/api/v1/room/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjUzMzI1NjI5LCJleHAiOjE2NTMzMjkyMjksInVzZXJOYW1lIjoiKzk5ODkzMjE1ODAwMCIsImlzcyI6IkRBVlJfQkFOSyJ9.atDTC62Gv35raTtW7iM2d7l_Uy0HEmWaZhCkKE7tQ_I

{
  "id": "1",
  "name": "JETBRAINS ROOM",
  "capacity": "30"
}

###
DELETE http://localhost:8080/api/v1/room/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjUzMzI1NjI5LCJleHAiOjE2NTMzMjkyMjksInVzZXJOYW1lIjoiKzk5ODkzMjE1ODAwMCIsImlzcyI6IkRBVlJfQkFOSyJ9.atDTC62Gv35raTtW7iM2d7l_Uy0HEmWaZhCkKE7tQ_I
